"""Custom exceptions for the BRD Generator Backend API.

This module defines domain-specific exceptions for clear error handling
throughout the application.
"""


class BRDGenerationError(Exception):
    """Raised when BRD generation fails.
    
    This exception is raised when the BRD generation process encounters
    an error that prevents successful completion, such as invalid OpenAI
    responses or processing failures.
    """
    pass


class OpenAIServiceError(Exception):
    """Raised when OpenAI API communication fails.
    
    This exception is raised when there are issues communicating with
    the OpenAI API, including authentication failures, rate limiting,
    network errors, or service unavailability.
    """
    pass


class ValidationError(Exception):
    """Raised when input validation fails.
    
    This exception is raised when request validation fails, such as
    missing required fields or invalid data formats.
    """
    pass


class GeminiAPIError(Exception):
    """Raised when Gemini API communication fails.
    
    This exception is raised when there are issues communicating with
    the Gemini API, including authentication failures, network errors,
    or service unavailability.
    """
    pass


class GeminiTimeoutError(GeminiAPIError):
    """Raised when Gemini API request exceeds timeout.
    
    This exception is raised when a Gemini API request takes longer
    than the configured timeout period.
    """
    pass


class GeminiRateLimitError(GeminiAPIError):
    """Raised when Gemini API rate limit is exceeded.
    
    This exception is raised when the Gemini API returns a rate limit
    error, indicating too many requests have been made.
    """
    pass


class ConstraintValidationError(Exception):
    """Raised when constraint validation fails.
    
    This exception is raised when the constraints generated by Gemini
    do not match the expected schema or contain invalid data.
    """
    pass


class ChunkingError(Exception):
    """Raised when text chunking fails.
    
    This exception is raised when the chunking process encounters
    an error that prevents successful text splitting, such as
    invalid text format or processing failures.
    """
    pass


class TextTooShortError(ChunkingError):
    """Raised when text is below minimum chunkable size.
    
    This exception is raised when attempting to chunk text that
    is too short to be meaningfully split into chunks.
    """
    pass


class TrackingSessionNotFoundError(Exception):
    """Raised when tracking session is not found.
    
    This exception is raised when attempting to access a tracking
    session that doesn't exist or has expired.
    """
    pass


class TrackingStorageError(Exception):
    """Raised when tracking storage operation fails.
    
    This exception is raised when there are issues with storing
    or retrieving tracking data, such as memory errors or
    concurrent access issues.
    """
    pass


class AggregationError(Exception):
    """Raised when chunk result aggregation fails.
    
    This exception is raised when the aggregation process encounters
    an error while combining results from multiple chunks.
    """
    pass


class EmptyChunkResultsError(AggregationError):
    """Raised when no chunk results are available to aggregate.
    
    This exception is raised when attempting to aggregate an empty
    list of chunk results, indicating extraction failures.
    """
    pass
